feat: #139 support showing VMware virtual machines in machine list an…
casdoor/awesome-auth pull request #140
Opened 2024-12-18 14:34 UTC by Gexinyu2333

When a provider adds resources in the form of VMware on the providers interface. As shown below:
![b596834870087c86e5de667c2f823e6](https://github.com/user-attachments/assets/8dc126a2-947b-460f-a371-e1e1a3ca5163)

The Client ID is a virtual machine ID of VMware Workstation Pro belonging to the provider; Client secure is the credential for VMware Workstation Pro REST service, in the form of {username}: {password}
If the VMware Workstation Pro REST service of the provider host is enabled, all virtual machine information in the provider's VMware Workstation Pro will be displayed on the machines page. As shown in the following figure:
![e53f78b1ea8c4d359878b1752c2b653](https://github.com/user-attachments/assets/9014469d-d8a0-43fa-8d03-22aa253f5d6f)

2024-12-25 16:09 UTC, hsluoyz requested changes
Demo video?

2024-12-25 16:09 UTC, hsluoyz commented on object/machine.go
> +		clientMachines, err2 := (*client).GetMachines()
Should not change this

2024-12-25 16:09 UTC, hsluoyz commented on object/machine.go
> +		clientMachine, err2 := (*client).GetMachine(name)
Should not change this

2024-12-25 16:09 UTC, hsluoyz commented on service/aliyun.go
> +func NewMachineAliyunClient(accessKeyId string, accessKeySecret string, region string) (MachineAliyunClient, error) {
Should not change this

2024-12-25 16:09 UTC, hsluoyz commented on service/util.go
> +func ExtractFileName(path string) string {
Go std lib should have this func

2024-12-25 16:09 UTC, hsluoyz commented on service/vmware.go
> +// you may not use this file except in compliance with the License.
Not correct Apache header

2024-12-25 16:09 UTC, hsluoyz commented on service/vmware.go
> +	if len(vmList) == 0 {
Remove this if

2024-12-25 16:09 UTC, hsluoyz commented on service/vmware.go
> +		machine, err := client.GetMachine(name)
Doesn't GetMachines already return JSON of all objects? Why call GetMachine in for loop?

2024-12-25 16:09 UTC, hsluoyz commented on service/vmware.go
> +	url := "http://localhost:8697/api/vms"
`http://localhost:8697` should be a configurable field in frontend

2024-12-25 16:18 UTC, hsluoyz requested changes

2024-12-25 16:18 UTC, hsluoyz commented on service/vmware.go
> +type MachineVMwareClient struct {
Vmware

2024-12-26 04:59 UTC, hsluoyz commented
@Gexinyu2333 rebase your code to resolve the conflicts:

![image](https://github.com/user-attachments/assets/bf198a48-981e-4ef0-95e6-3e2c51c6ba9f)

2024-12-26 07:43 UTC, Gexinyu2333 commented
This is a demo video.

https://github.com/user-attachments/assets/158576ba-9429-4a36-8124-8987c68d4dda

2024-12-26 08:33 UTC, merged