feat: improve and add database setting in asset pages
casdoor/awesome-auth pull request #66
Opened 2024-03-03 16:02 UTC by leo220yuyaodog

2024-03-03 17:59 UTC, hsluoyz requested changes

2024-03-03 17:59 UTC, hsluoyz commented on web/src/Conf.js
> +  dbgateUrl: "http://localhost:5001",
It's not AuthConfig

2024-03-03 17:59 UTC, hsluoyz commented on web/src/Setting.js
> +  {label: "MySQL", value: "mysql"},
value and label should be the same, we store what users see in UI

2024-03-03 17:59 UTC, hsluoyz commented on web/src/AssetListPage.js
> +          {text: "MySQL", value: "mysql"},
Generate filter from Setting.DataBaseTypes ?

2024-03-03 17:59 UTC, hsluoyz commented on web/src/Setting.js
> +export const DataBaseTypes = [
DataBaseTypes -> getDatabaseTypes

2024-03-03 17:59 UTC, hsluoyz commented on web/src/AssetListPage.js
> +          {text: "RDP", value: "rdp"},
Also define Setting.getMachineTypes

2024-03-03 17:59 UTC, hsluoyz commented on web/src/AssetListPage.js
> +    if (params.category !== undefined && params.category !== null) {
Use `if (params.category)`

2024-03-03 17:59 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +                  {label: "RDP", value: "rdp"},
Use Setting.getMachineTypes

2024-03-03 17:59 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +                  {label: "SSH", value: "ssh"},
Value also use label, VNC, RDP, etc.

2024-03-03 17:59 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +    case "vnc":
VNC, SSH, RDP

2024-03-03 17:59 UTC, hsluoyz commented on object/asset.go
>  	Tag         string `xorm:"varchar(100)" json:"tag"`
Add Type

2024-03-03 17:59 UTC, hsluoyz commented on object/asset.go
>  	Ip          string `xorm:"varchar(100)" json:"ip"`
Endpoint

2024-03-03 17:59 UTC, hsluoyz commented on object/asset.go
> +	Protocol        string       `xorm:"varchar(20)" json:"protocol"`
Protocol -> Type

2024-03-03 17:59 UTC, hsluoyz commented on object/asset.go
> +	DatabaseType    string `xorm:"varchar(100)" json:"databaseType"`
DatabaseType -> Type

2024-03-03 17:59 UTC, hsluoyz commented on object/asset.go
> +	DatabaseUrl     string `xorm:"varchar(200)" json:"databaseUrl"`
What's DatabaseUrl and UseDatabaseUrl ?

2024-03-04 02:15 UTC, leo220yuyaodog commented on object/asset.go
> +	DatabaseUrl     string `xorm:"varchar(200)" json:"databaseUrl"`
dbgate support advanced users can customize connection statements through `DatabaseUrl`. I will remove them first, the added fields have nothing to do with this pr. I'm going to complete it in next pr.

2024-03-04 04:45 UTC, hsluoyz approved these changes

2024-03-04 04:45 UTC, merged