feat: support intranet desktop connect
casdoor/awesome-auth pull request #75
Opened 2024-04-05 06:12 UTC by leo220yuyaodog

2024-04-05 07:51 UTC, hsluoyz requested changes

2024-04-05 07:51 UTC, hsluoyz commented on object/asset.go
> +	if asset == nil {
Determine null outside of it

2024-04-05 07:51 UTC, hsluoyz commented on proxy/client/client.go
> +	"github.com/beego/beego/logs"
We don't use `github.com/beego/beego/logs`, always return error

2024-04-05 07:51 UTC, hsluoyz commented on proxy/client/client.go
> +	// 通知server开始监听这些app
All English

2024-04-05 07:51 UTC, hsluoyz commented on proxy/tunnel/message.go
> +	TypeServerHeartbeat MessageType = "1001"
Don't encode types. Just use descriptive string

2024-04-05 07:51 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +      assset.hostname = "";
asset, not assset

2024-04-05 07:51 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +      isIntranet: false,
Remove isIntranet

2024-04-05 07:51 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +                  <Input value={asset.remoteHostname || Setting.ServerUrl} onChange={e => {
Why `|| Setting.ServerUrl`? No need

2024-04-05 07:51 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +                  {Setting.getLabel(i18next.t("Asset:Hostname"), i18next.t("Asset:Hostname - Tooltip"))} :
Remove asset.hostname, use asset.name is enough

2024-04-05 07:51 UTC, hsluoyz commented on proxy/starter.go
> +	proxyPort := util.ParseInt(conf.GetConfigString("proxyPort"))
GetConfigInt

2024-04-05 07:51 UTC, hsluoyz commented on proxy/tunnel/conn.go
> +		// 链接断开或发生异常时断开
All English

2024-04-05 07:51 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +                  <Input value={asset.remoteHostname || Setting.ServerUrl} onChange={e => {
If I change the `remoteHostname`'s value now, will it work immediately? Or need to restart Go backend?

2024-04-05 12:20 UTC, hsluoyz requested changes

2024-04-05 12:20 UTC, hsluoyz commented on conf/app.conf
> +startMode =
Remove startMode

2024-04-05 12:20 UTC, hsluoyz commented on controllers/tunnel.go
> +		configuration.SetParameter("hostname", conf.GatewayAddr.IP.String())
GatewayAddr can be nil

2024-04-05 12:20 UTC, hsluoyz commented on proxy/starter.go
> +	proxyServer, err := server.NewProxyServer("Casvisor Proxy Server", conf.GatewayAddr.Port)
GatewayAddr can be nil

2024-04-05 12:20 UTC, hsluoyz commented on proxy/starter.go
> +			conf.GatewayAddr.IP.String(),
GatewayAddr can be nil

2024-04-05 12:20 UTC, hsluoyz commented on proxy/starter.go
> +		panic(fmt.Errorf("failed to get asset by hostname %s", err))
panic(err)

2024-04-05 12:20 UTC, hsluoyz commented on proxy/starter.go
> +func StartMode() string {
Remove StartMode

2024-04-05 12:20 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +            isIntranet: newAsset.hostname !== "",
Remove isIntranet

2024-04-05 12:20 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +    const {asset, isIntranet} = this.state;
Remove isIntranet

2024-04-05 12:20 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +          <Switch checked={isIntranet} onChange={checked => {
Remove isIntranet

2024-04-05 12:20 UTC, hsluoyz commented on conf/conf.go
> +	GatewayAddr, err = net.ResolveTCPAddr("tcp", GetConfigString("gatewayEndpoint"))
If gatewayEndpoint is "" (empty string), means disable it

2024-04-05 12:20 UTC, hsluoyz commented on conf/conf.go
> +		fmt.Println("parse gatewayAddr failed")
If gatewayEndpoint is not empty string, and failed, then panic

2024-04-05 12:20 UTC, hsluoyz commented on main.go
> +
Remove empty line

2024-04-05 12:20 UTC, hsluoyz commented on object/asset.go
> +
No new line

2024-04-05 12:20 UTC, hsluoyz commented on proxy/client/client.go
> +	"github.com/beego/beego/logs"
@leo220yuyaodog not fixed

2024-04-05 12:20 UTC, hsluoyz commented on object/asset.go
> +func GetAssetByName(name string) (*Asset, error) {
Use `GetAsset()`, don't create new API, the owner param is the Casdoor org, you can get it

2024-04-07 04:02 UTC, leo220yuyaodog commented
@hsluoyz ready for review

2024-04-07 05:51 UTC, hsluoyz approved these changes

2024-04-07 05:51 UTC, merged