feat:add "upload and downlod RDP file" feature(#45
casdoor/awesome-auth pull request #96
Opened 2024-05-30 15:24 UTC by tulutulupi

Add functionality to upload an RDP file to generate an asset and download the existing asset's RDP file.

2024-05-31 06:38 UTC, tulutulupi commented
@hsluoyz ready for review

2024-05-31 13:55 UTC, hsluoyz requested changes

2024-05-31 13:55 UTC, hsluoyz commented on web/src/AssetListPage.js
> +    name = `machine_${Setting.getRandomName()}`, displayName = `New Machine - ${Setting.getRandomName()}`) {
Write new code, don't mess with this code

2024-05-31 13:55 UTC, hsluoyz commented on web/src/AssetListPage.js
> +      if (trimmedLine.startsWith("full address:s:")) {
Use regex, let ChatGPT write it, ChatGPT can do better

Just use asset as return value

2024-05-31 13:55 UTC, hsluoyz commented on web/src/AssetListPage.js
> +    const props = {
Refer to Casdoor similar code

2024-05-31 13:55 UTC, hsluoyz commented on web/src/locales/de/data.json
> +    "Upload (.rdp)": "Upload (.rdp)"
Only translate "Upload"

2024-05-31 13:55 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +  downLoadRDPFile(asset) {
RDP -> Rdp for everywhere except labels

2024-05-31 13:55 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +          {(asset.type === "RDP" && this.state.mode !== "add") ?
Don't change existing code

2024-05-31 13:55 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +              defaultValue={this.getDefaultPort(asset.type)}
Don't change existing code

2024-05-31 15:10 UTC, tulutulupi commented
@hsluoyz ready for review again

2024-05-31 15:24 UTC, hsluoyz requested changes

2024-05-31 15:24 UTC, hsluoyz commented on web/src/AssetEditPage.js
> +              {i18next.t("asset:Download Rdp file")}
UI is RDP

2024-05-31 15:24 UTC, hsluoyz commented on web/src/AssetListPage.js
> +      Setting.showMessage("error", i18next.t("asset:Invalid Rdp file"));
UI is RDP

2024-05-31 15:59 UTC, tulutulupi commented
@hsluoyz ready for review again

2024-06-01 00:57 UTC, hsluoyz approved these changes

2024-06-01 01:01 UTC, merged